### ISSUE TITLE
A few issues to flag

### ISSUE THREAD

**Issue by carlosdp** [wizardsdao/wiz-gnosis-module#1]
Hey, cool module! I think I identified a few issues you might want to check out on a cursory look at the contract though:

- It looks like [this require statement](https://github.com/wizardsdao/wiz-gnosis-module/blob/119b73c551db549c85557d78369ed066aef7302f/contracts/Wiz.sol#L156-L159) makes it so the proposer can't get their collateral back if the transaction ends up reverting (the only way to free the funds would be to invalidate the transaction after the fact, moving the funds to the safe, and manually paying the proposer back), which could happen because of outside factors (ie. withdrawing funds from a contract that was drained between the time the transaction was queued and when it was approved)
- I think you meant to use `invalidationQuorum` [here](https://github.com/wizardsdao/wiz-gnosis-module/blob/master/contracts/Wiz.sol#L178) instead of `5`
- The contract doesn't seem to track whether an address has already voted, so anyone could just call `invalidate` `invalidationQuorum` number of times and invalidate any transaction without actually reaching a quorum.
- The readme says "Whenever a transaction is queued it is placed on a time-lock for a determined amount of time that blocks all executions until the time-lock has expired.", which seems to imply the contract requires transactions are approved and executions in one ordered queue, but that doesn't appear to be the case in the contract itself.

Hope this is helpful!

**Comment by wizdao** [comment]
Thanks for the thorough review! I addressed your concerns in commit 953b12f

**Comment by carlosdp** [comment]
Cool!

@wizdao you still need to remove that `require` on line 158 though. The require will make the entire transaction revert, resulting in none of the previous logic happening. Remove that and it'll work as you intended.

**Comment by wizdao** [comment]
@carlosdp you're right! small oversight on my part and updated in 0f97066. Appreciate the help, really good stuff. let me know if you have any other thoughts

**Comment by wizdao** [comment]
@carlosdp
